"""Recipe Generator tab — build a pantry and generate nutritious recipes."""

import streamlit as st

from src.nutrition.models import (
    GeneratedRecipe,
    HealthProfile,
    NutritionData,
    PantryItem,
)
from src.nutrition.fda_guidelines import compute_dv_percentages

# ── Food emoji helper (shared with snap tab pattern) ──────────────────────────
_FOOD_EMOJI_MAP: dict[str, str] = {
    "chicken": "🍗", "beef": "🥩", "steak": "🥩", "pork": "🥩",
    "lamb": "🥩", "turkey": "🦃", "fish": "🐟", "salmon": "🐟",
    "tuna": "🐟", "shrimp": "🍤", "egg": "🥚", "eggs": "🥚",
    "tofu": "🫘", "tempeh": "🫘",
    "spinach": "🥬", "broccoli": "🥦", "carrot": "🥕", "tomato": "🍅",
    "potato": "🥔", "sweet potato": "🍠", "corn": "🌽", "onion": "🧅",
    "garlic": "🧄", "pepper": "🫑", "avocado": "🥑", "cucumber": "🥒",
    "lettuce": "🥬", "kale": "🥬", "mushroom": "🍄", "celery": "🥬",
    "apple": "🍎", "banana": "🍌", "orange": "🍊", "lemon": "🍋",
    "grape": "🍇", "strawberry": "🍓", "mango": "🥭", "peach": "🍑",
    "blueberry": "🫐",
    "bread": "🍞", "rice": "🍚", "pasta": "🍝", "noodle": "🍜",
    "oat": "🥣", "oatmeal": "🥣", "flour": "🌾", "tortilla": "🌮",
    "cereal": "🥣", "cracker": "🍘",
    "milk": "🥛", "cheese": "🧀", "yogurt": "🫙", "butter": "🧈",
    "cream": "🥛",
    "bean": "🫘", "beans": "🫘", "lentil": "🫘", "lentils": "🫘",
    "chickpea": "🫘", "peanut": "🥜", "almond": "🌰", "nut": "🥜",
    "nuts": "🥜", "walnut": "🌰",
    "oil": "🫙", "salt": "🧂", "sugar": "🍬", "honey": "🍯",
    "sauce": "🫙", "broth": "🍲", "stock": "🍲", "water": "💧",
    "soup": "🍲", "salsa": "🍅", "hummus": "🫘",
}


def food_emoji(name: str) -> str:
    lower = name.lower()
    matches = [(kw, em) for kw, em in _FOOD_EMOJI_MAP.items() if kw in lower]
    if matches:
        return max(matches, key=lambda x: len(x[0]))[1]
    return "🥘"


def _source_badge(source: str) -> str:
    cfg = {
        "label_scan": ("#E8F5E9", "#1B5E20", "📷 Label"),
        "photo_id":   ("#E3F2FD", "#1565C0", "🍽️ Photo"),
        "manual":     ("#F3E5F5", "#6A1B9A", "✏️ Manual"),
    }
    bg, color, label = cfg.get(source, ("#F5F5F5", "#555", source))
    return (
        f'<span style="background:{bg};color:{color};padding:2px 9px;'
        f'border-radius:100px;font-size:0.72rem;font-weight:700;">{label}</span>'
    )


def _recipe_to_text(recipe: GeneratedRecipe) -> str:
    """Serialize a GeneratedRecipe to a plain-text download string."""
    lines = [
        f"{'=' * 50}",
        f"  {recipe.title}",
        f"  Serves: {recipe.servings}",
        f"{'=' * 50}",
        "",
        "INGREDIENTS",
        "-" * 30,
    ]
    for ing in recipe.ingredients_used:
        lines.append(f"  • {ing}")
    if recipe.additional_ingredients_needed:
        lines.append("")
        lines.append("YOU MAY ALSO NEED")
        lines.append("-" * 30)
        for ing in recipe.additional_ingredients_needed:
            lines.append(f"  ○ {ing}")
    lines += ["", "INSTRUCTIONS", "-" * 30]
    for j, step in enumerate(recipe.instructions, 1):
        lines.append(f"  {j}. {step}")
    if recipe.nutrition_highlights:
        lines += ["", "NUTRITION HIGHLIGHTS", "-" * 30]
        for h in recipe.nutrition_highlights:
            lines.append(f"  ★ {h}")
    if recipe.tips:
        lines += ["", "TIP", "-" * 30, f"  {recipe.tips}"]
    lines += ["", "─" * 50, "  Generated by NutriScan · AI estimates only", "─" * 50]
    return "\n".join(lines)


def _init_session_state():
    if "pantry_items" not in st.session_state:
        st.session_state.pantry_items = []
    if "generated_recipe" not in st.session_state:
        st.session_state.generated_recipe = None


def _render_pantry_builder():
    tab_label, tab_photo, tab_manual = st.tabs(["📷 Scan a Label", "🍽️ Snap Food", "✏️ Add Manually"])

    with tab_label:
        uploaded_labels = st.file_uploader(
            "Upload nutrition label(s) — select multiple photos at once",
            type=["jpg", "jpeg", "png", "heic", "heif", "webp"],
            key="recipe_label_upload",
            accept_multiple_files=True,
        )
        n = len(uploaded_labels) if uploaded_labels else 0
        btn_label = f"Add {n} Label{'s' if n != 1 else ''}" if n else "Add from Label"
        if uploaded_labels and st.button(btn_label, key="add_label",
                                         use_container_width=True, type="primary"):
            from src.vision.label_reader import extract_label_with_vision
            from PIL import Image
            from src.ocr.extractor import extract
            added = 0
            failed = 0
            low_conf = 0
            with st.spinner(f"🔍 Reading {n} label(s)..."):
                for uploaded_label in uploaded_labels:
                    try:
                        uploaded_label.seek(0)
                        image_bytes = uploaded_label.read()
                        uploaded_label.seek(0)
                        nutrition = None
                        vision_result = extract_label_with_vision(image_bytes)
                        if vision_result is not None and vision_result.fields_parsed > 0:
                            nutrition = vision_result.nutrition
                            if vision_result.confidence < 0.5:
                                low_conf += 1
                        else:
                            uploaded_label.seek(0)
                            image = Image.open(uploaded_label).convert("RGB")
                            ocr_result = extract(image)
                            uploaded_label.seek(0)
                            nutrition = ocr_result.nutrition
                            if ocr_result.confidence == "low":
                                low_conf += 1
                        item = PantryItem(
                            name=uploaded_label.name.rsplit(".", 1)[0] or "Scanned Item",
                            source="label_scan",
                            nutrition=nutrition,
                            quantity="1 serving",
                        )
                        st.session_state.pantry_items.append(item)
                        added += 1
                    except Exception:
                        failed += 1
            if added:
                st.toast(f"Added {added} label{'s' if added != 1 else ''}", icon="✅")
            if low_conf:
                st.warning(f"{low_conf} label(s) had low confidence — review values before generating a recipe.")
            if failed:
                st.error(f"{failed} label(s) failed to read. Try manual entry for those.")
            if added:
                st.rerun()

    with tab_photo:
        food_photos = st.file_uploader(
            "Upload food photo(s) — select multiple photos at once",
            type=["jpg", "jpeg", "png", "heic", "heif", "webp"],
            key="recipe_food_upload",
            accept_multiple_files=True,
        )
        n = len(food_photos) if food_photos else 0
        btn_label = f"Identify & Add from {n} Photo{'s' if n != 1 else ''}" if n else "Identify & Add"
        if food_photos and st.button(btn_label, key="add_photo",
                                     use_container_width=True, type="primary"):
            from src.vision.food_identifier import identify_food
            total_added = 0
            failed = 0
            with st.spinner(f"🧠 Identifying food items in {n} photo(s)..."):
                for food_photo in food_photos:
                    try:
                        foods = identify_food(food_photo.getvalue())
                        for f in foods:
                            grams = f.get("estimated_grams")
                            item = PantryItem(
                                name=f["name"],
                                source="photo_id",
                                estimated_grams=grams,
                                quantity=f"{grams}g" if grams else "",
                            )
                            st.session_state.pantry_items.append(item)
                            total_added += 1
                    except Exception:
                        failed += 1
            if total_added:
                st.toast(f"Added {total_added} item(s) from {n} photo(s)", icon="✅")
            if failed:
                st.error(f"{failed} photo(s) failed. Try manual entry for those.")
            if total_added:
                st.rerun()

    with tab_manual:
        col_name, col_qty = st.columns([2, 1])
        with col_name:
            manual_name = st.text_input(
                "Ingredient name", key="manual_ingredient",
                placeholder="e.g. Canned black beans",
            )
        with col_qty:
            manual_qty = st.text_input(
                "Quantity", key="manual_qty",
                placeholder="e.g. 1 can",
            )
        if (
            st.button("➕ Add Ingredient", key="add_manual",
                      use_container_width=True, type="primary")
            and manual_name
        ):
            st.session_state.pantry_items.append(
                PantryItem(name=manual_name, source="manual", quantity=manual_qty)
            )
            st.toast(f"Added: {manual_name}", icon="✅")
            st.rerun()


def _render_pantry_display():
    items = st.session_state.pantry_items

    st.markdown(f"""
    <div style="display:flex;align-items:center;justify-content:space-between;
                padding:0.4rem 0;margin:0.5rem 0 0.6rem;
                border-bottom:2px solid rgba(46,125,50,0.2);">
        <div style="display:flex;align-items:center;gap:8px;">
            <span style="font-size:1rem;">🧺</span>
            <span style="font-weight:700;font-size:0.95rem;color:#4CAF50;">Your Pantry</span>
            <span style="background:rgba(46,125,50,0.12);color:#2E7D32;padding:1px 10px;
                         border-radius:100px;font-size:0.75rem;font-weight:700;">
                {len(items)} item{"s" if len(items) != 1 else ""}
            </span>
        </div>
    </div>""", unsafe_allow_html=True)

    if not items:
        st.markdown("""
        <div style="background:rgba(128,128,128,0.06);border:1px dashed #C8E6C9;border-radius:12px;
                    padding:1.5rem;color:inherit;opacity:0.5;text-align:center;font-size:0.87rem;">
            <div style="font-size:1.8rem;margin-bottom:0.4rem;">🧺</div>
            Add ingredients above to start building your pantry.
        </div>""", unsafe_allow_html=True)
        return

    for i, item in enumerate(items):
        col_ico, col_name, col_qty, col_badge, col_rm = st.columns([0.4, 2.5, 1.5, 1.2, 0.9])
        with col_ico:
            st.markdown(
                f'<div style="font-size:1.3rem;padding:5px 0;text-align:center;">'
                f'{food_emoji(item.name)}</div>',
                unsafe_allow_html=True,
            )
        with col_name:
            st.markdown(
                f'<div style="font-weight:700;font-size:0.9rem;color:inherit;'
                f'padding:6px 0;">{item.name}</div>',
                unsafe_allow_html=True,
            )
        with col_qty:
            st.markdown(
                f'<div style="font-size:0.85rem;color:inherit;opacity:0.7;padding:6px 0;">'
                f'{item.quantity or "—"}</div>',
                unsafe_allow_html=True,
            )
        with col_badge:
            st.markdown(
                f'<div style="padding:6px 0;">{_source_badge(item.source)}</div>',
                unsafe_allow_html=True,
            )
        with col_rm:
            if st.button("✕ Remove", key=f"remove_{i}"):
                removed = st.session_state.pantry_items.pop(i)
                st.toast(f"Removed: {removed.name}", icon="🗑️")
                st.rerun()

    st.markdown("<div style='margin-top:0.25rem;'></div>", unsafe_allow_html=True)
    if st.button("🗑️ Clear All", key="clear_pantry"):
        st.session_state.pantry_items = []
        st.session_state.generated_recipe = None
        st.toast("Pantry cleared", icon="🗑️")
        st.rerun()


def _render_recipe_generation():
    st.divider()
    items = st.session_state.pantry_items

    if len(items) < 2:
        if items:
            st.markdown("""
            <div style="background:rgba(255,179,0,0.1);border:1px solid #FFB300;border-radius:10px;
                        padding:0.75rem 1rem;color:#E65100;font-size:0.87rem;">
                ⚠️ Add at least <strong>2 ingredients</strong> to generate a recipe.
            </div>""", unsafe_allow_html=True)
        return

    st.markdown("""
    <div style="display:flex;align-items:center;gap:8px;padding:0.35rem 0;
                margin-bottom:0.75rem;border-bottom:2px solid rgba(46,125,50,0.2);">
        <span style="font-size:1rem;">🍳</span>
        <span style="font-weight:700;font-size:0.95rem;color:#4CAF50;">Generate Recipe</span>
    </div>""", unsafe_allow_html=True)

    col_gen, col_regen = st.columns(2)
    with col_gen:
        generate = st.button(
            "✨ Generate Recipe", type="primary", key="gen_recipe", use_container_width=True
        )
    with col_regen:
        regenerate = False
        if st.session_state.generated_recipe:
            regenerate = st.button("🔄 Regenerate", key="regen_recipe", use_container_width=True)

    if generate or regenerate:
        with st.spinner("👨‍🍳 Creating your personalized recipe..."):
            try:
                from src.llm.groq_client import GroqClient
                health_profile = st.session_state.get("health_profile", HealthProfile())
                client = GroqClient()
                recipe = client.generate_recipe(items, health_profile)
                st.session_state.generated_recipe = recipe
                st.rerun()
            except Exception as e:
                st.error(f"Recipe generation failed: {e}")
                return

    recipe: GeneratedRecipe | None = st.session_state.generated_recipe
    if not recipe:
        return

    # ── Recipe card header ────────────────────────────────────────────────────
    st.markdown(f"""
    <div style="background:linear-gradient(135deg,#1A4D1E,#388E3C);color:white;
                padding:1.4rem 1.8rem;border-radius:16px;margin:1rem 0 1rem;
                box-shadow:0 4px 18px rgba(46,125,50,0.3);">
        <div style="font-size:0.72rem;font-weight:700;opacity:0.65;
                    letter-spacing:1.2px;text-transform:uppercase;margin-bottom:5px;">
            ✨ Generated Recipe
        </div>
        <div style="font-size:1.55rem;font-weight:900;line-height:1.2;margin-bottom:4px;">
            {recipe.title}
        </div>
        <div style="opacity:0.78;font-size:0.87rem;">🍽️ Serves {recipe.servings}</div>
    </div>""", unsafe_allow_html=True)

    # ── Download button ───────────────────────────────────────────────────────
    recipe_text = _recipe_to_text(recipe)
    safe_title = recipe.title.replace(" ", "_").replace("/", "-")[:40]
    st.download_button(
        label="📥 Download Recipe",
        data=recipe_text,
        file_name=f"{safe_title}.txt",
        mime="text/plain",
        key="download_recipe",
    )

    # ── Two-column: ingredients | instructions ────────────────────────────────
    col_ing, col_inst = st.columns([1, 1.5])

    with col_ing:
        st.markdown("""
        <div style="font-weight:700;font-size:0.92rem;color:#4CAF50;
                    padding:0.35rem 0;border-bottom:2px solid rgba(46,125,50,0.2);
                    margin-bottom:0.65rem;">
            🧺 Ingredients Used
        </div>""", unsafe_allow_html=True)
        for ing in recipe.ingredients_used:
            em = food_emoji(ing)
            st.markdown(f"""
            <div style="display:flex;align-items:flex-start;gap:8px;
                        padding:5px 0;border-bottom:1px solid #F0F7F0;">
                <span style="font-size:1rem;flex-shrink:0;">{em}</span>
                <span style="font-size:0.87rem;color:inherit;">{ing}</span>
            </div>""", unsafe_allow_html=True)

        if recipe.additional_ingredients_needed:
            st.markdown("""
            <div style="font-weight:700;font-size:0.88rem;color:#E65100;
                        margin:1rem 0 0.5rem;padding:0.3rem 0;
                        border-bottom:2px solid #FFE0B2;">
                ➕ You May Also Need
            </div>""", unsafe_allow_html=True)
            for ing in recipe.additional_ingredients_needed:
                em = food_emoji(ing)
                st.markdown(f"""
                <div style="display:flex;align-items:flex-start;gap:8px;
                            padding:5px 0;border-bottom:1px solid #FFF8F0;">
                    <span style="font-size:1rem;flex-shrink:0;">{em}</span>
                    <span style="font-size:0.87rem;color:inherit;opacity:0.7;">{ing}</span>
                </div>""", unsafe_allow_html=True)

    with col_inst:
        st.markdown("""
        <div style="font-weight:700;font-size:0.92rem;color:#4CAF50;
                    padding:0.35rem 0;border-bottom:2px solid rgba(46,125,50,0.2);
                    margin-bottom:0.65rem;">
            📋 Instructions
        </div>""", unsafe_allow_html=True)
        for j, step in enumerate(recipe.instructions, 1):
            st.markdown(f"""
            <div style="display:flex;gap:12px;align-items:flex-start;
                        padding:0.6rem 0;border-bottom:1px solid #F0F7F0;">
                <div style="width:24px;height:24px;background:#2E7D32;color:white;
                            border-radius:50%;display:flex;align-items:center;
                            justify-content:center;font-size:11px;font-weight:800;
                            flex-shrink:0;margin-top:2px;">{j}</div>
                <div style="font-size:0.87rem;color:inherit;line-height:1.55;">{step}</div>
            </div>""", unsafe_allow_html=True)

    # ── Nutrition breakdown ───────────────────────────────────────────────────
    if recipe.estimated_nutrition:
        st.markdown("""
        <div style="font-weight:700;font-size:0.92rem;color:#4CAF50;
                    padding:0.35rem 0;border-bottom:2px solid rgba(46,125,50,0.2);
                    margin:1.25rem 0 0.75rem;">
            📊 Estimated Nutrition (per serving)
        </div>""", unsafe_allow_html=True)
        dv = compute_dv_percentages(recipe.estimated_nutrition)
        import pandas as pd
        dv_display = {k.replace("_", " ").title(): v for k, v in dv.items()}
        df = pd.DataFrame(
            {"Nutrient": list(dv_display.keys()), "% Daily Value": list(dv_display.values())}
        ).set_index("Nutrient")
        st.bar_chart(df, color="#43A047")

    # ── Highlights + tips ─────────────────────────────────────────────────────
    if recipe.nutrition_highlights:
        chips = " &nbsp;·&nbsp; ".join(
            f'<strong>{h}</strong>' for h in recipe.nutrition_highlights
        )
        st.markdown(f"""
        <div style="background:rgba(46,125,50,0.12);border-radius:10px;padding:0.65rem 1rem;
                    font-size:0.85rem;color:#4CAF50;margin-top:0.5rem;">
            🌟 <strong>Highlights:</strong> {chips}
        </div>""", unsafe_allow_html=True)

    if recipe.tips:
        st.markdown(f"""
        <div style="background:rgba(255,179,0,0.1);border-left:4px solid #FFB300;
                    border-radius:0 10px 10px 0;padding:0.7rem 1rem;
                    font-size:0.87rem;color:#E65100;margin-top:0.6rem;">
            💡 <strong>Tip:</strong> {recipe.tips}
        </div>""", unsafe_allow_html=True)

    st.caption("*Nutrition values are AI-estimated and may not be precise.*")


def render_recipe_tab():
    """Main entry point for the Recipe Generator tab."""
    st.markdown("""
    <div style="margin-bottom:0.5rem;">
        <div style="font-size:1.25rem;font-weight:800;color:#4CAF50;">🍳 Recipe Generator</div>
        <div style="font-size:0.85rem;color:inherit;opacity:0.7;margin-top:2px;">
            Add ingredients from label scans or photos, then generate a nutritious recipe
            from what you have — great for making the most of limited pantry items.
        </div>
    </div>""", unsafe_allow_html=True)

    _init_session_state()

    st.markdown("""
    <div style="display:flex;align-items:center;gap:8px;padding:0.35rem 0;
                margin-bottom:0.6rem;border-bottom:2px solid rgba(46,125,50,0.2);">
        <span style="font-size:1rem;">➕</span>
        <span style="font-weight:700;font-size:0.95rem;color:#4CAF50;">Add Ingredients</span>
    </div>""", unsafe_allow_html=True)

    _render_pantry_builder()
    st.divider()
    _render_pantry_display()
    _render_recipe_generation()
